name: Build Dev
on:
    push:
        branches:
            - dev
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # TODO:私有包指定域
            - name: Use Node.js
              uses: actions/setup-node@v3
            #   with:
            #       always-auth: true
            #       node-version: "16.x"
            #       registry-url: https://npm.pkg.github.com
            #       scope: "@org"

            # - name: Install dependencies
            #   run: npm ci
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

            - name: Install && Build
              run: |
                  npm install
                  npm run build:dev

            # TODO:部署位置
            - name: GrayEnv
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.DEV_HOST }}
                  username: ${{ secrets.DEV_USER }}
                  key: ${{ secrets.DEV_KEY }}
                  source: dist/*
                  target: /www/wwwroot/iruxu/i/dev
